### ISSUE TITLE
Unknown command: SORT

### ISSUE THREAD

**Issue by Sebijk** [b1gMail/b1gMailServer#10] opened 2024-01-13 12:36 UTC
It seems that SORT command ( https://datatracker.ietf.org/doc/html/rfc5256 ) is currently unsupported by b1gMailServer.

**Comment by pschlan** [comment] 2024-01-17 13:44
b1gMailServer is not advertising support for the extension specified in that RFC...

**Comment by pschlan** [comment] 2024-01-17 13:44
Closing as this is not a bug

**Closed by pschlan** 2024-01-17 13:44 UTC
